<DOCTYPE html>

<p id='contact-anchor'> <?= $formTitle?></p>

<form>
  <div class="form-group">
    <label for="exampleInputName">Vos noms/prénoms</label>
    <input type="name" class="form-control" id="exampleInputName">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Votre adresse E-mail</label>
    <input type="email" class="form-control" id="exampleInputEmail1" >
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Votre message</label>
    <input type="message" class="form-control" id="exampleInputMessage" >
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">J'ai compris. En envoyant ce formulaire, j'autorise le destinataire à utiliser mes données personnelles pour me répondre. Mentions Légales *</label>
  </div>
  <button type="submit" class="btn btn-primary">Valider</button>
</form>

</html>