

<?php ob_start();
$leadTitle= 'Edwige Genty';
$leadText='PHP/Symfony development';
$formTitle='Contactez-moi'?>

<div class="container">

    <p>Les derniers articles</p>

    <div class="row">

    <?php foreach ($resultat as $tab){?>
        
        <div class="col-md-6">
            <div class="card mb-4 shadow-sm">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title> <?= $tab['title']?></title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em"> <?= $tab['title']?></text></svg>
                <div class="card-body">
                <p class="card-text">
                    <?= $tab['chapo']?></p>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted"> <?= $tab['category']?></small>
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">Lire l'article</button>
                    </div>
                </div>
                </div>
            </div>
        </div>

    <?php }  ?>

           
    </div>
</div>

<form>
        <?php $formTitle='Contactez moi';
        require ('formTemplate.phtml')?>
</form>

<?php $content = ob_get_clean();

require('layout.php');?>

